@startuml Massage Reservation Use Case Diagram
left to right direction
actor "User" as user
rectangle "Massage Reservation" as MassageReservation {
    usecase "Register" as register
    usecase "View\nMassage" as viewMassage
    usecase "Manage\nReservation" as manageReservation
    usecase "Manage\nMassage" as manageMassage
}

user -- register
user -- viewMassage
user -- manageReservation

actor "Admin" as admin
register -- admin
manageMassage -- admin
manageReservation -- admin

@enduml